### ISSUE TITLE
Fix navigation push animation

### ISSUE THREAD

**Issue by zacwood9** [zosman1/masontoday#5]
## Summary

The navigation push animation when the detail view comes on screen looks really rough right now. Right now, as soon as the animation starts, the "< Back" button immediately appears on screen in the top left corner. Ideally, the "< Back" button on the navigation bar should smoothly transition onto the screen with the detail view. 

## Helpful links
https://wix.github.io/react-native-navigation/v2/#/docs/options/TopBar

**Comment by zosman1** [comment]
Closed with 3ae067045df18fe4d45eb38274e7fc16180f13f7
